#! /bin/bash

OLSRDCONFIG=/etc/olsrd/olsrd.conf
HOSTS=/var/run/hosts_olsr
SECONDARIES=

. ./config

#
# Get main IP
#
mainip=( $(cat ${OLSRDCONFIG} | grep "MainIp") )
MYIP=${mainip[1]}
if [ "${MYIP}" = "" ]; then
  echo "Missing IP"
  exit 1
fi

ZONEFILE="/etc/bind/${ZONE}.zone.db"

#
# Create zone file header
#
cat > ${ZONEFILE} <<__EOF__
;
; Zone ${ZONE}.mesh
;
\$TTL 60
\$ORIGIN ${ZONE}.mesh.
@	IN	SOA	dns0.${ZONE}.mesh. root.${ZONE}.mesh. (
			$(date +%s) ; Serial
			3600 ; Refresh
			300 ; Retry
			604800 ; Expire
			60 ) ; TTL
;
@ IN  NS	dns0
dns IN  A ${MYIP}
__EOF__

#
# Add secondary DNS servers which will be notified when we update
#
if [ "${SECONDARIES}" != "" ]; then
  count=0
  for ip in ${SECONDARIES}
  do
    count=$(($count + 1))
    echo "@ IN  NS  dns${count}" >> ${ZONEFILE}
    echo "dns${count}  IN  A ${ip}" >> ${ZONEFILE}
  done
fi

#
# Create an entry for each valid IP/HOST line
#
cat ${HOSTS} | while read LINE
do
  words=( $LINE )
  ip=${words[0]}
  host=${words[1]}
  if [[ ${ip} =~ ^10\. && ! ${host} =~ \. ]]; then
    echo "$host	IN 	A	$ip" >> ${ZONEFILE}
  fi
done

#
# Reload the zone
#
/usr/sbin/rndc reload ${ZONE}.mesh
